name: EasyAsyncPG CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: easyasyncpg
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install latest version of Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Add Poetry to $PATH
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Get Poetry version
        run: poetry --version
      - name: Install dependencies
        run: |
          poetry lock
          poetry install --all-extras
      - name: Ruff
        run: |
          poetry run ruff .
      - name: MyPy
        run: |
          poetry run mypy .
      - name: Test with pytest
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: easyasyncpg
          DB_PORT: 5432
        run: |
          poetry run coverage run -m pytest tests/ -vvvv
      - name: Run Coverage export XML
        run: |
          poetry run coverage xml -o ./coverage.xml
      - name: Run Coverage Report
        run: |
          poetry run coverage report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}